class Hero < ApplicationRecord
    has_one :stat


    def self.test
    array = [
    {"id":953,"name":"Adams","icon":"i","stats":{"hp":"5645","atk":"1462","def":"1216","speed":"90"},"element":"Darkness","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":468,"name":"Afos","icon":"i","stats":{"hp":"5271","atk":"1364","def":"1131","speed":"88"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":1045,"name":"Alexei","icon":"i","stats":{"hp":"6181","atk":"736","def":"1395","speed":"49"},"element":"Frost","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":589,"name":"Alos","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Machine","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":457,"name":"Amedon","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Fire","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":1201,"name":"Anastasia","icon":"i","stats":{"hp":"7584","atk":"1102","def":"935","speed":"32"},"element":"Frost","type":"Support","rarity":"Fated","jp_only":"Global Only"},
    {"id":864,"name":"Annie","icon":"i","stats":{"hp":"5472","atk":"1644","def":"855","speed":"51"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1094,"name":"April","icon":"i","stats":{"hp":"6930","atk":"1013","def":"856","speed":"32"},"element":"Light","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":417,"name":"Arno","icon":"i","stats":{"hp":"5774","atk":"697","def":"1215","speed":"68"},"element":"Machine","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":609,"name":"Asiki","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Nature","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":1038,"name":"Astarte","icon":"i","stats":{"hp":"5637","atk":"1460","def":"1214","speed":"89"},"element":"Nature","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1178,"name":"Baileysh","icon":"i","stats":{"hp":"4984","atk":"1502","def":"935","speed":"32"},"element":"Darkness","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":1101,"name":"Baraka","icon":"i","stats":{"hp":"4800","atk":"1705","def":"737","speed":"114"},"element":"Machine","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":151,"name":"Bathory","icon":"i","stats":{"hp":"6016","atk":"1809","def":"940","speed":"56"},"element":"Frost","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":828,"name":"Bayer","icon":"i","stats":{"hp":"4565","atk":"1373","def":"855","speed":"31"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":517,"name":"Bellum","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Frost","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":713,"name":"Benten","icon":"i","stats":{"hp":"5661","atk":"1465","def":"1218","speed":"92"},"element":"Nature","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":56,"name":"Bernadette","icon":"i","stats":{"hp":"5992","atk":"1804","def":"936","speed":"53"},"element":"Frost","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":1186,"name":"Bernavas","icon":"i","stats":{"hp":"6784","atk":"802","def":"1435","speed":"72"},"element":"Machine","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":356,"name":"Berol","icon":"i","stats":{"hp":"5782","atk":"698","def":"1217","speed":"69"},"element":"Nature","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":604,"name":"Blaska","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Nature","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":932,"name":"Bongkoos","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"110"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":728,"name":"Brook","icon":"i","stats":{"hp":"5661","atk":"1465","def":"1218","speed":"92"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":225,"name":"Buck","icon":"i","stats":{"hp":"5790","atk":"700","def":"1218","speed":"70"},"element":"Darkness","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":304,"name":"Carlos","icon":"i","stats":{"hp":"4280","atk":"1284","def":"801","speed":"30"},"element":"Fire","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":1209,"name":"Chati","icon":"i","stats":{"hp":"6784","atk":"802","def":"1535","speed":"52"},"element":"Nature","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":564,"name":"Clement","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Fire","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":325,"name":"Colin","icon":"i","stats":{"hp":"5279","atk":"1366","def":"1133","speed":"89"},"element":"Machine","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":507,"name":"Colossal Drill Mk.I","icon":"i","stats":{"hp":"5766","atk":"695","def":"1214","speed":"67"},"element":"Machine","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":973,"name":"Corgi","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"110"},"element":"Fire","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1066,"name":"Cybele","icon":"i","stats":{"hp":"6906","atk":"1008","def":"853","speed":"29"},"element":"Light","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":658,"name":"David Johnson","icon":"i","stats":{"hp":"5661","atk":"1465","def":"1218","speed":"92"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":669,"name":"Degas","icon":"i","stats":{"hp":"6205","atk":"742","def":"2077","speed":"32"},"element":"Frost","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":451,"name":"Deradan","icon":"i","stats":{"hp":"4256","atk":"1278","def":"797","speed":"107"},"element":"Fire","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":641,"name":"Deva","icon":"i","stats":{"hp":"4392","atk":"1556","def":"675","speed":"112"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":484,"name":"Dio","icon":"i","stats":{"hp":"5766","atk":"695","def":"1214","speed":""},"element":"Frost","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":574,"name":"Duman","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Machine","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":108,"name":"Duncan","icon":"i","stats":{"hp":"5661","atk":"1465","def":"1218","speed":"92"},"element":"Machine","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":534,"name":"Eclipse","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Darkness","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":402,"name":"Edith","icon":"i","stats":{"hp":"5766","atk":"695","def":"1214","speed":"67"},"element":"Nature","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":1159,"name":"Emma","icon":"i","stats":{"hp":"7592","atk":"1103","def":"836","speed":"73"},"element":"Darkness","type":"Support","rarity":"Fated","jp_only":"Global Only"},
    {"id":387,"name":"Eorile","icon":"i","stats":{"hp":"4264","atk":"1280","def":"798","speed":"108"},"element":"Nature","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":462,"name":"Fames","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Fire","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":996,"name":"Fergie","icon":"i","stats":{"hp":"6914","atk":"1010","def":"763","speed":"70"},"element":"Machine","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":758,"name":"Firis","icon":"i","stats":{"hp":"6205","atk":"742","def":"1399","speed":"52"},"element":"Light","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":407,"name":"Forbeta","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":"107"},"element":"Nature","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":1003,"name":"Freesia","icon":"i","stats":{"hp":"6189","atk":"738","def":"1306","speed":"70"},"element":"Light","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":172,"name":"Gale","icon":"i","stats":{"hp":"5287","atk":"1368","def":"1134","speed":"90"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":96,"name":"Garff","icon":"i","stats":{"hp":"6816","atk":"809","def":"1540","speed":"56"},"element":"Light","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":392,"name":"Gellmann","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Nature","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":479,"name":"Genoi","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":201,"name":"Glenn","icon":"i","stats":{"hp":"5790","atk":"700","def":"1218","speed":"70"},"element":"Machine","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":191,"name":"Godin","icon":"i","stats":{"hp":"5790","atk":"700","def":"1301","speed":"50"},"element":"Frost","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":512,"name":"Gregory","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":765,"name":"Griesel","icon":"i","stats":{"hp":"6197","atk":"740","def":"1398","speed":"51"},"element":"Nature","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":903,"name":"Guter","icon":"i","stats":{"hp":"6189","atk":"738","def":"1306","speed":"70"},"element":"Fire","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":422,"name":"Guy","icon":"i","stats":{"hp":"5095","atk":"1529","def":"797","speed":"47"},"element":"Machine","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":497,"name":"Hachion","icon":"i","stats":{"hp":"5095","atk":"1529","def":"797","speed":"47"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":1080,"name":"Hawkeye","icon":"i","stats":{"hp":"6181","atk":"736","def":"1395","speed":"49"},"element":"Light","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":319,"name":"Hekin","icon":"i","stats":{"hp":"4280","atk":"1284","def":"801","speed":"110"},"element":"Fire","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":1010,"name":"Heowon","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"30"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":252,"name":"Iden","icon":"i","stats":{"hp":"4112","atk":"1451","def":"634","speed":"110"},"element":"Nature","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":237,"name":"Iris","icon":"i","stats":{"hp":"6462","atk":"951","def":"717","speed":"70"},"element":"Light","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":960,"name":"Ivan","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"110"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":375,"name":"Jean","icon":"i","stats":{"hp":"4272","atk":"1282","def":"799","speed":"109"},"element":"Fire","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":180,"name":"Jinai","icon":"i","stats":{"hp":"5016","atk":"1510","def":"940","speed":"36"},"element":"Nature","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":829,"name":"Jinn","icon":"i","stats":{"hp":"4808","atk":"1707","def":"738","speed":"115"},"element":"Machine","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":554,"name":"Kale","icon":"i","stats":{"hp":"6438","atk":"945","def":"797","speed":"27"},"element":"Darkness","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":594,"name":"Kalinent","icon":"i","stats":{"hp":"5766","atk":"695","def":"1297","speed":"47"},"element":"Fire","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":502,"name":"Kamodin","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Frost","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":889,"name":"Karin","icon":"i","stats":{"hp":"6922","atk":"1011","def":"855","speed":"31"},"element":"Nature","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":549,"name":"Kasoke","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Light","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":310,"name":"Kaya","icon":"i","stats":{"hp":"6462","atk":"951","def":"801","speed":"30"},"element":"Nature","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":980,"name":"Kinberra","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"110"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":746,"name":"Kirina","icon":"i","stats":{"hp":"4392","atk":"1556","def":"675","speed":"112"},"element":"Frost","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":533,"name":"Laman","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":"107"},"element":"Fire","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":772,"name":"Leger","icon":"i","stats":{"hp":"6922","atk":"1011","def":"855","speed":"31"},"element":"Light","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":794,"name":"Lepin","icon":"i","stats":{"hp":"6922","atk":"1011","def":"855","speed":"31"},"element":"Frost","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":584,"name":"Leto","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":""},"element":"Machine","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":704,"name":"Liechtenstein","icon":"i","stats":{"hp":"6205","atk":"742","def":"1399","speed":"52"},"element":"Light","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":127,"name":"Liffy","icon":"i","stats":{"hp":"4280","atk":"1284","def":"801","speed":"110"},"element":"Darkness","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":397,"name":"Lucinin","icon":"i","stats":{"hp":"5766","atk":"695","def":"1297","speed":"47"},"element":"Nature","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":910,"name":"Luke","icon":"i","stats":{"hp":"6189","atk":"738","def":"2074","speed":"30"},"element":"Fire","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":688,"name":"Lyungen","icon":"i","stats":{"hp":"6205","atk":"742","def":"1308","speed":"72"},"element":"Machine","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1143,"name":"Magi","icon":"i","stats":{"hp":"5992","atk":"1804","def":"936","speed":"53"},"element":"Fire","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":1151,"name":"Mahar","icon":"i","stats":{"hp":"6792","atk":"804","def":"2285","speed":"33"},"element":"Machine","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":599,"name":"Mamanti","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":"107"},"element":"Nature","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":489,"name":"Maxim","icon":"i","stats":{"hp":"4248","atk":"1277","def":"796","speed":"106"},"element":"Frost","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":808,"name":"Metron","icon":"i","stats":{"hp":"4565","atk":"1373","def":"855","speed":"31"},"element":"Light","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":818,"name":"Minea","icon":"i","stats":{"hp":"6922","atk":"1011","def":"765","speed":"71"},"element":"Darkness","type":"Support","rarity":"Legendary","jp_only":"Global Only"},    
    {"id":344,"name":"Mirrty","icon":"i","stats":{"hp":"5782","atk":"698","def":"1217","speed":"69"},"element":"Machine","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":527,"name":"Molot","icon":"i","stats":{"hp":"5758","atk":"693","def":"1213","speed":"66"},"element":"Frost","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":925,"name":"Monica","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"110"},"element":"Frost","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":337,"name":"Morris","icon":"i","stats":{"hp":"5279","atk":"1366","def":"113","speed":"89"},"element":"Machine","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":381,"name":"Navid","icon":"i","stats":{"hp":"6446","atk":"947","def":"714","speed":"68"},"element":"Nature","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":569,"name":"Ned","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":"107"},"element":"Machine","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":217,"name":"Nermash","icon":"i","stats":{"hp":"4112","atk":"1451","def":"634","speed":"110"},"element":"Darkness","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":1017,"name":"Nero","icon":"i","stats":{"hp":"4368","atk":"1550","def":"672","speed":"109"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1087,"name":"Nika","icon":"i","stats":{"hp":"6205","atk":"742","def":"1308","speed":"72"},"element":"Machine","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":966,"name":"Obellia","icon":"i","stats":{"hp":"6914","atk":"1010","def":"763","speed":"70"},"element":"Frost","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":368,"name":"Oos","icon":"i","stats":{"hp":"5111","atk":"1533","def":"799","speed":"49"},"element":"Fire","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":740,"name":"Otard","icon":"i","stats":{"hp":"5661","atk":"1465","def":"1218","speed":"92"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":895,"name":"Pan","icon":"i","stats":{"hp":"6922","atk":"1011","def":"765","speed":"71"},"element":"Fire","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":436,"name":"Patrick","icon":"i","stats":{"hp":"4256","atk":"1278","def":"797","speed":"107"},"element":"Frost","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":1073,"name":"Pitbull","icon":"i","stats":{"hp":"6181","atk":"736","def":"1305","speed":"69"},"element":"Fire","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":138,"name":"Rachel","icon":"i","stats":{"hp":"6216","atk":"1609","def":"1340","speed":"96"},"element":"Fire","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":579,"name":"Raferit","icon":"i","stats":{"hp":"4088","atk":"1446","def":"630","speed":""},"element":"Machine","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":838,"name":"Ramge","icon":"i","stats":{"hp":"7600","atk":"1105","def":"837","speed":"74"},"element":"Darkness","type":"Support","rarity":"Fated","jp_only":"Global Only"},
    {"id":696,"name":"Reedmarie","icon":"i","stats":{"hp":"4573","atk":"1375","def":"856","speed":"112"},"element":"Frost","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":294,"name":"Rera","icon":"i","stats":{"hp":"5008","atk":"1507","def":"938","speed":"115"},"element":"Nature","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":917,"name":"Risis","icon":"i","stats":{"hp":"4557","atk":"1371","def":"854","speed":"30"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":426,"name":"Robert","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":286,"name":"Rudley","icon":"i","stats":{"hp":"6208","atk":"1607","def":"1338","speed":"95"},"element":"Nature","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":1194,"name":"Sabrina","icon":"i","stats":{"hp":"6184","atk":"1602","def":"1335","speed":"92"},"element":"Fire","type":"Attack","rarity":"Fated","jp_only":"Global Only"},
    {"id":522,"name":"Santos","icon":"i","stats":{"hp":"4256","atk":"1278","def":"797","speed":"107"},"element":"Frost","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":946,"name":"Scarlet","icon":"i","stats":{"hp":"5464","atk":"1643","def":"854","speed":"50"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1031,"name":"Sefer","icon":"i","stats":{"hp":"6906","atk":"1008","def":"762","speed":"69"},"element":"Darkness","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":231,"name":"Seir","icon":"i","stats":{"hp":"5287","atk":"1368","def":"1134","speed":"90"},"element":"Frost","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":939,"name":"Sernando","icon":"i","stats":{"hp":"5464","atk":"1643","def":"854","speed":"50"},"element":"Light","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":734,"name":"Sharpei","icon":"i","stats":{"hp":"4392","atk":"1556","def":"675","speed":"112"},"element":"Darkness","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1120,"name":"Shell","icon":"i","stats":{"hp":"7600","atk":"1105","def":"837","speed":"74"},"element":"Machine","type":"Support","rarity":"Fated","jp_only":"Global Only"},
    {"id":159,"name":"Shufraken","icon":"i","stats":{"hp":"6816","atk":"809","def":"1440","speed":"76"},"element":"Darkness","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":856,"name":"Spica","icon":"i","stats":{"hp":"6197","atk":"740","def":"1307","speed":"71"},"element":"Frost","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1167,"name":"Talia","icon":"i","stats":{"hp":"7592","atk":"1103","def":"936","speed":"33"},"element":"Nature","type":"Support","rarity":"Fated","jp_only":"Global Only"},
    {"id":752,"name":"Tantalo","icon":"i","stats":{"hp":"6205","atk":"742","def":"2077","speed":"32"},"element":"Nature","type":"Defense","rarity":"Legendary","jp_only":"Global Only"},
    {"id":636,"name":"Tashume","icon":"i","stats":{"hp":"5255","atk":"1360","def":"1129","speed":"86"},"element":"Nature","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":441,"name":"Tentol","icon":"i","stats":{"hp":"5774","atk":"697","def":"1298","speed":"48"},"element":"Fire","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":989,"name":"Tereia","icon":"i","stats":{"hp":"6914","atk":"1010","def":"763","speed":"70"},"element":"Darkness","type":"Support","rarity":"Legendary","jp_only":"Global Only"},
    {"id":532,"name":"Timur","icon":"i","stats":{"hp":"5758","atk":"693","def":"1921","speed":"26"},"element":"Frost","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":446,"name":"Tomedes","icon":"i","stats":{"hp":"6446","atk":"947","def":"714","speed":"68"},"element":"Fire","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":331,"name":"Topaki","icon":"i","stats":{"hp":"5782","atk":"698","def":"1217","speed":"69"},"element":"Frost","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":1131,"name":"Uloom","icon":"i","stats":{"hp":"6800","atk":"806","def":"2287","speed":"34"},"element":"Machine","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":431,"name":"Ulrich","icon":"i","stats":{"hp":"6438","atk":"945","def":"713","speed":"67"},"element":"Machine","type":"Support","rarity":"Rare","jp_only":"Global Only"},
    {"id":1110,"name":"Valarr","icon":"i","stats":{"hp":"6800","atk":"806","def":"1437","speed":"74"},"element":"Nature","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":782,"name":"Valentina","icon":"i","stats":{"hp":"5008","atk":"1507","def":"938","speed":"35"},"element":"Frost","type":"Chaos","rarity":"Fated","jp_only":"Global Only"},
    {"id":350,"name":"Venato","icon":"i","stats":{"hp":"4104","atk":"1449","def":"632","speed":"109"},"element":"Nature","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":412,"name":"Vincent","icon":"i","stats":{"hp":"5271","atk":"1364","def":"1131","speed":"88"},"element":"Machine","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":1024,"name":"Vinity","icon":"i","stats":{"hp":"4368","atk":"1550","def":"672","speed":"109"},"element":"Nature","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":614,"name":"Wagni","icon":"i","stats":{"hp":"5766","atk":"695","def":"1922","speed":"27"},"element":"Light","type":"Defense","rarity":"Rare","jp_only":"Global Only"},
    {"id":362,"name":"Weiler","icon":"i","stats":{"hp":"4104","atk":"1449","def":"632","speed":"109"},"element":"Frost","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":245,"name":"Wilkes","icon":"i","stats":{"hp":"4280","atk":"1284","def":"801","speed":"30"},"element":"Darkness","type":"Chaos","rarity":"Rare","jp_only":"Global Only"},
    {"id":793,"name":"Xiakhan","icon":"i","stats":{"hp":"6808","atk":"807","def":"1438","speed":"75"},"element":"Frost","type":"Defense","rarity":"Fated","jp_only":"Global Only"},
    {"id":1052,"name":"Yao","icon":"i","stats":{"hp":"4368","atk":"1550","def":"672","speed":"109"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":1059,"name":"Yorm","icon":"i","stats":{"hp":"4549","atk":"1369","def":"853","speed":"29"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":559,"name":"Yulled","icon":"i","stats":{"hp":"5263","atk":"1362","def":"1130","speed":"87"},"element":"Light","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":875,"name":"Zarienne","icon":"i","stats":{"hp":"4565","atk":"1373","def":"855","speed":"111"},"element":"Machine","type":"Chaos","rarity":"Legendary","jp_only":"Global Only"},
    {"id":258,"name":"Zeon","icon":"i","stats":{"hp":"5287","atk":"1368","def":"1134","speed":"90"},"element":"Fire","type":"Attack","rarity":"Rare","jp_only":"Global Only"},
    {"id":882,"name":"Zeradin","icon":"i","stats":{"hp":"5472","atk":"1644","def":"855","speed":"51"},"element":"Fire","type":"Attack","rarity":"Legendary","jp_only":"Global Only"},
    {"id":473,"name":"Zetok","icon":"i","stats":{"hp":"4096","atk":"1448","def":"631","speed":"108"},"element":"Frost","type":"Chaos","rarity":"Rare","jp_only":"Global Only"}]


    array.each do |hero|
        heros = Hero.create(name: hero[:name], element: hero[:element], hero_type: hero[:type], rarity: hero[:rarity])
        stats = Stat.create(hero_id: heros.id, hp: hero[:stats][:hp], atk: hero[:stats][:atk], def: hero[:stats][:def], speed: hero[:stats][:speed])
    end

    end 



end
